#!/bin/bash
# install.sh
# Installs the Obsidian session sync hook for Claude Code.
#
# What it does:
#   1. Copies scripts to ~/.claude/hooks/
#   2. Merges the SessionEnd hook into ~/.claude/settings.json
#   3. Creates the vault folder structure
#   4. Verifies everything works

set -e

HOOK_DIR="${HOME}/.claude/hooks"
SETTINGS_FILE="${HOME}/.claude/settings.json"
VAULT_PATH="${HOME}/vault"
SESSIONS_DIR="${VAULT_PATH}/Claude Sessions"

echo "═══════════════════════════════════════════════════════"
echo "  Obsidian Session Sync — Installer"
echo "═══════════════════════════════════════════════════════"
echo ""

# ─── Step 1: Copy scripts ────────────────────────────────────────────────────
echo "→ Installing scripts to ${HOOK_DIR}..."
mkdir -p "$HOOK_DIR"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cp "$SCRIPT_DIR/obsidian-session-sync.py" "$HOOK_DIR/"
cp "$SCRIPT_DIR/obsidian-hook.sh" "$HOOK_DIR/"
cp "$SCRIPT_DIR/my-memory-prompt-hook.py" "$HOOK_DIR/"
cp "$SCRIPT_DIR/my-memory-check.sh" "$HOOK_DIR/"
chmod +x "$HOOK_DIR/obsidian-hook.sh"
chmod +x "$HOOK_DIR/obsidian-session-sync.py"
chmod +x "$HOOK_DIR/my-memory-prompt-hook.py"
chmod +x "$HOOK_DIR/my-memory-check.sh"

echo "  ✓ obsidian-session-sync.py"
echo "  ✓ obsidian-hook.sh"
echo "  ✓ my-memory-prompt-hook.py"
echo "  ✓ my-memory-check.sh"

# ─── Step 2: Update settings.json ────────────────────────────────────────────
echo ""
echo "→ Configuring Claude Code hooks..."

HOOK_CMD="bash ~/.claude/hooks/obsidian-hook.sh"

if [ -f "$SETTINGS_FILE" ]; then
    # Check if hook already exists
    if grep -q "obsidian-hook" "$SETTINGS_FILE" 2>/dev/null; then
        echo "  ✓ Hook already configured in settings.json"
    else
        # Use python to safely merge the hook into existing settings
        python3 -c "
import json, sys

with open('$SETTINGS_FILE', 'r') as f:
    settings = json.load(f)

hooks = settings.setdefault('hooks', {})

hook_entry = {
    'hooks': [{
        'type': 'command',
        'command': '$HOOK_CMD',
        'timeout': 10000
    }]
}

memory_hook_entry = {
    'hooks': [{
        'type': 'command',
        'command': 'bash ~/.claude/hooks/my-memory-check.sh',
    }]
}

# Register on both SessionEnd and Stop for reliability
for event in ['SessionEnd', 'Stop']:
    event_hooks = hooks.setdefault(event, [])
    exists = any(
        any(h.get('command', '').find('obsidian-hook') != -1 for h in entry.get('hooks', []))
        for entry in event_hooks
    )
    if not exists:
        event_hooks.append(hook_entry.copy())

# Register UserPromptSubmit for /my-memory
usp = hooks.setdefault('UserPromptSubmit', [])
exists = any(
    any(h.get('command', '').find('my-memory') != -1 for h in entry.get('hooks', []))
    for entry in usp
)
if not exists:
    usp.append(memory_hook_entry)

with open('$SETTINGS_FILE', 'w') as f:
    json.dump(settings, f, indent=2)
print('  ✓ Added SessionEnd + Stop + UserPromptSubmit hooks to settings.json')
"
    fi
else
    # Create fresh settings.json
    python3 -c "
import json

hook_entry = {
    'hooks': [{
        'type': 'command',
        'command': '$HOOK_CMD',
        'timeout': 10000
    }]
}

settings = {
    'hooks': {
        'UserPromptSubmit': [{
            'hooks': [{
                'type': 'command',
                'command': 'bash ~/.claude/hooks/my-memory-check.sh',
            }]
        }],
        'SessionEnd': [hook_entry],
        'Stop': [hook_entry.copy()]
    }
}
with open('$SETTINGS_FILE', 'w') as f:
    json.dump(settings, f, indent=2)
print('  ✓ Created settings.json with all hooks')
"
fi

# ─── Step 3: Create vault structure ──────────────────────────────────────────
echo ""
echo "→ Setting up vault at ${VAULT_PATH}..."

mkdir -p "${SESSIONS_DIR}/Projects"
mkdir -p "${SESSIONS_DIR}/Daily"

# Create index if it doesn't exist
INDEX_FILE="${SESSIONS_DIR}/_index.md"
if [ ! -f "$INDEX_FILE" ]; then
    cat > "$INDEX_FILE" << 'EOF'
---
type: claude-moc
tags:
  - claude-moc
---

# Claude Sessions — Index

> Auto-generated by Claude Code session hooks.
> Each session creates/updates a note under Projects/<name>/<date>.

EOF
    echo "  ✓ Created _index.md"
else
    echo "  ✓ _index.md already exists"
fi

echo "  ✓ Projects/ directory"
echo "  ✓ Daily/ directory"

# ─── Step 4: Verify ──────────────────────────────────────────────────────────
echo ""
echo "→ Verifying installation..."

# Test the Python script can be invoked
if python3 "$HOOK_DIR/obsidian-session-sync.py" --list-projects 2>/dev/null; then
    echo "  ✓ Script runs successfully"
else
    echo "  ⚠ Script test had issues (may be fine — no .claude/projects yet)"
fi

# Verify settings
if python3 -c "
import json
with open('$SETTINGS_FILE') as f:
    s = json.load(f)
assert 'SessionEnd' in s.get('hooks', {}), 'No SessionEnd hook'
print('  ✓ settings.json is valid and contains SessionEnd hook')
" 2>/dev/null; then
    true
else
    echo "  ⚠ Could not verify settings.json"
fi

echo ""
echo "═══════════════════════════════════════════════════════"
echo "  ✓ Installation complete!"
echo "═══════════════════════════════════════════════════════"
echo ""
echo "  Vault:    ${VAULT_PATH}/Claude Sessions/"
echo "  Scripts:  ${HOOK_DIR}/"
echo "  Settings: ${SETTINGS_FILE}"
echo "  Logs:     ~/.claude/obsidian-sync.log"
echo ""
echo "  How it works:"
echo "    When a Claude Code session ends → hook fires →"
echo "    parses transcript → writes Obsidian note under"
echo "    Projects/<project-name>/<date>.md"
echo ""
echo "  Utilities:"
echo "    Convert JSONL to readable JSON:"
echo "      python3 ~/.claude/hooks/obsidian-session-sync.py --convert <file.jsonl>"
echo ""
echo "    List all Claude Code projects:"
echo "      python3 ~/.claude/hooks/obsidian-session-sync.py --list-projects"
echo ""
